accounts/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from . import views


app_name = 'accounts'


urlpatterns = [
    url(
        regex=r"^memberships/$",
        view=views.memberships,
        name="memberships"
    ),
    url(
        regex=r"^settings/$",
        view=views.account_settings,
        name="account_settings"
    ),
    url(
        regex=r'^(?P<sponsor_pk>\d+)/$',
        view=views.detail,
        name='detail'
    ),
]

billing/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from . import views


app_name = 'billing'


urlpatterns = [
    url(
        regex=r'^checkout/(?P<event_pk>\d+)/$',
        view=views.checkout,
        name='checkout'
    ),
    url(
        regex=r'^update_auto_renew/$',
        view=views.update_auto_renew,
        name='update_auto_renew'
    ),
]

trip/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from . import views


admin.site.site_header = "TRIP Administration"
admin.site.site_title = "TRIP Administration"
admin.site.index_title = "TRIP"


urlpatterns = [
    # ADMIN
    url(
        r'^hidden/secure/trip/admin/',
        include(admin.site.urls)
    ),

    # GENERAL
    url(
        regex=r'^$',
        view=views.home,
        name='home'
    ),

    # ACCOUNTS
    url(
        r'^accounts/',
        include('accounts.urls', namespace='accounts')
    ),

    # AUTHENTICATION
    url(
        r'^auth/',
        include('authentication.urls', namespace='authentication')
    ),

    # BILLING
    url(
        r'^billing/',
        include('billing.urls', namespace='billing')
    ),

    # CONTACT
    url(
        r'^contact/',
        include('contact.urls', namespace='contact')
    ),

    # EVENTS
    url(
        r'^events/',
        include('events.urls', namespace='events')
    ),

    # SPONSORS
    url(
        regex=r'^sponsors/$',
        view=views.sponsors,
        name='sponsors'
    ),
]


if settings.DEBUG:
    urlpatterns += [] + static(settings.STATIC_URL,
                               document_root=settings.STATIC_ROOT)
    urlpatterns += [] + static(settings.MEDIA_URL,
                               document_root=settings.MEDIA_ROOT)
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

accounts/models.py
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin)
from django.core.mail import send_mail
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible
from django.utils.functional import cached_property
from django.utils.translation import ugettext_lazy as _

from billing.models import Customer, Plan, Subscription
from core.models import TimeStampedModel

# Create your models here.


def logo_upload_loc(instance, filename):
    """Stores the company logo in <company_name>/logos/filename."""
    return "{0}/logos/{1}".format(instance.name, filename)


class MyUserManager(BaseUserManager):
    def _create_user(self, email, first_name, last_name, password,
                     is_staff, is_superuser, **extra_fields):
        """Creates and saves a User with the given email, first name,
        last name, and password."""
        now = timezone.now()

        if not email:
            raise ValueError('Users must have an email.')
        elif not first_name:
            raise ValueError('Users must have a first name.')
        elif not last_name:
            raise ValueError('Users must have a last name.')

        user = self.model(email=self.normalize_email(email),
                          first_name=first_name, last_name=last_name,
                          is_staff=is_staff, is_active=True,
                          is_superuser=is_superuser, last_login=now,
                          date_joined=now, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, first_name, last_name, password=None,
                    **extra_fields):
        return self._create_user(email, first_name, last_name, password,
                                 is_staff=False, is_superuser=False,
                                 **extra_fields)

    def create_superuser(self, email, first_name, last_name, password,
                         **extra_fields):
        user = self._create_user(email, first_name, last_name, password,
                                 is_staff=True, is_superuser=True,
                                 **extra_fields)
        cu = Customer.objects.create(user=user, account_balance=0)
        plan = Plan.objects.get(name='Admin')
        Subscription.objects.create(customer=cu, plan=plan)
        return user


@python_2_unicode_compatible
class MyUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(max_length=120, unique=True)
    first_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50, blank=True)

    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)
    modified = models.DateTimeField(_('last modified'), auto_now=True)

    is_active = models.BooleanField(_('active'), default=True)
    is_staff = models.BooleanField(_('staff'), default=False,
                                   help_text='Allows users to create events.')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = MyUserManager()

    class Meta:
        app_label = 'accounts'
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def __str__(self):
        return u"{0} {1}".format(self.first_name, self.last_name)

    @cached_property
    def get_full_name(self):
        """Returns the first_name plus the last_name, with a space in
        between."""
        return "{0} {1}".format(self.first_name, self.last_name)

    @cached_property
    def get_short_name(self):
        """Returns the first name for the user."""
        return str(self.first_name)

    def email_user(self, subject, message, from_email=None):
        """Sends an email to the user."""
        send_mail(subject, message, from_email, [self.email])

    def has_module_perms(self, app_label):
        """Does the user have permissions to view the app `app_label`?"""
        return True

    def has_perm(self, perm, obj=None):
        """Does the user have a specific permission?"""
        return True


class SponsorManager(models.Manager):
    def active(self):
        """Returns all active sponsors."""
        return super(SponsorManager, self).get_queryset().filter(
            is_active=True)


@python_2_unicode_compatible
class Sponsor(TimeStampedModel):
    name = models.CharField(_('company name'), max_length=100)
    logo = models.ImageField(_('company logo'),
                             upload_to=logo_upload_loc,
                             blank=True,
                             help_text='''Please upload an image with
                              sizes: (W - 488px | H - 150px)''')
    website = models.URLField(max_length=150, null=True, blank=True)
    affiliates = models.ManyToManyField(MyUser,
                                        related_name='sponsor_affiliates',
                                        blank=True)

    is_active = models.BooleanField(_('active'), default=True)

    objects = SponsorManager()

    class Meta:
        app_label = 'accounts'
        verbose_name = _('sponsor')
        verbose_name_plural = _('sponsors')

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        """Returns the url for the user."""
        return reverse_lazy('accounts:detail', kwargs={"sponsor_pk": self.pk})

    @property
    def company_logo(self):
        """Returns the logo of the user. If there is no logo, a default one
        will be rendered."""
        if self.logo:
            return "{0}{1}".format(settings.MEDIA_URL, self.logo)
        return settings.STATIC_URL + 'img/default-company-logo.jpg'

accounts/forms.py
"""
Glossary of accounts/forms.py:

- Account settings form
- MyUser change form (admin only)
"""

from __future__ import unicode_literals

try:
    from collections import OrderedDict
except ImportError:
    OrderedDict = None

from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.password_validation import validate_password
from django.db.models import Q
from django.utils.translation import ugettext_lazy as _

from .models import MyUser

# Create your forms here.


def clean_passwords(data, password1, password2):
    if password1 in data and password2 in data:
        if data[password1] != data[password2]:
            raise forms.ValidationError(
                _("You must type the same password each time."))
        validate_password(data[password2])
    return data[password2]


class AccountSettingsForm(forms.ModelForm):
    """A form used for users to update their account information."""
    email = forms.EmailField(
        label=_('Email'),
        widget=forms.EmailInput(),
        max_length=120
    )
    first_name = forms.CharField(
        label=_('First Name'),
        widget=forms.TextInput(),
        max_length=50
    )
    last_name = forms.CharField(
        label=_('Last Name'),
        widget=forms.TextInput(),
        max_length=50
    )
    password_new = forms.CharField(
        label=_("New Password"),
        widget=forms.PasswordInput(render_value=False),
        required=False
    )
    password_new_confirm = forms.CharField(
        label=_("New Password (again)"),
        widget=forms.PasswordInput(render_value=False),
        required=False
    )

    class Meta:
        model = MyUser
        fields = ('email', 'first_name', 'last_name',
                  'password_new', 'password_new_confirm',)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(AccountSettingsForm, self).__init__(*args, **kwargs)

    def clean_email(self):
        """Verify that the new email is not already taken."""
        value = self.cleaned_data['email'].lower()
        if self.initial.get('email') == value:
            return value
        if MyUser.objects.filter(
                Q(email__iexact=value) & ~Q(pk=self.user.pk)).exists():
            raise forms.ValidationError(
                _('This email is already taken. Please try a different one.'))
        return value

    def clean_password_new_confirm(self):
        if not self.cleaned_data['password_new_confirm'] == '':
            clean_passwords(data=self.cleaned_data,
                            password1="password_new",
                            password2="password_new_confirm")
        return self.cleaned_data['password_new_confirm']


class MyUserChangeForm(UserChangeForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field."""
    def __init__(self, *args, **kargs):
        super(MyUserChangeForm, self).__init__(*args, **kargs)
        # del self.fields['username']

    class Meta:
        model = MyUser
        fields = '__all__'

    def clean_email(self):
        """Verify that the new email is not already taken."""
        value = self.cleaned_data['email'].lower()
        if self.initial.get('email') == value:
            return value
        if MyUser.objects.filter(email__iexact=value).exists():
            raise forms.ValidationError(
                _('This email is already taken. Please try a different one.'))
        return value

accounts/views.py
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render
from django.views.decorators.cache import never_cache
from django.views.decorators.debug import sensitive_post_parameters

from billing.models import Customer, Plan, Subscription
from events.models import Event
from .forms import AccountSettingsForm
from .models import MyUser

# Create your views here.


@login_required
def detail(request, user_pk):
    user = get_object_or_404(MyUser, pk=user_pk)
    own_events = Event.objects.own(user=user)
    ctx = {
        'own_events': own_events,
        'user': user,
    }
    return render(request, 'accounts/detail.html', ctx)


@login_required
@never_cache
@sensitive_post_parameters()
def account_settings(request):
    user = request.user
    customer = Customer.objects.get(user=user)
    subscription = Subscription.objects.get(customer=customer)

    form = AccountSettingsForm(request.POST or None,
                               request.FILES or None,
                               instance=user, user=user)

    if request.method == 'POST' and form.is_valid():
        form.email = form.cleaned_data['email']
        password = form.cleaned_data['password_new_confirm']

        if password:
            current_user = form.user
            current_user.set_password(password)
            current_user.save()
            update_session_auth_hash(request, current_user)
        form.save()
        messages.success(request,
                         "You have successfully updated your profile.")
    ctx = {
        'form': form,
        'customer': customer,
        'subscription': subscription,
        'user': user,
    }
    return render(request, 'accounts/settings.html', ctx)


def memberships(request):
    plans = Plan.objects.active()
    return render(request, 'auth/memberships.html', {'plans': plans})

templates/accounts/detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}{% endblock title %}

{% block content %}
  <h3>Events sponsored</h3>
  <!-- table -->
  <div id="demo">
    <div class="table-responsive-vertical shadow-z-1">
      <table id="table" class="table table-hover table-mc-orange">
        <thead>
          <tr>
            <th>Name</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Link</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          {% for event in own_events %}
            <tr>
              <td data-title="Name">{{ event.name }}</td>
              <td data-title="Start Date">{{ event.event_start_date }}</td>
              <td data-title="End Date">{{ event.event_end_date }}</td>
              <td data-title="Link">
                <a href="{{ event.get_absolute_url }}">View event</a>
              </td>
              <td data-title="Status">{{ event.event_status }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  <!-- /table -->
{% endblock content %}

templates/accounts/settings.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %} / Settings{% endblock title %}

{% block content %}
  <img id="page-loader" style="position:absolute; top:50%; left:50%; display:none;" src="{% static 'img/loader.svg' %}" alt="Loader" />

  <div class="col-md-8 col-lg-8">
    <form class="form-validation" method="POST" action="{% url 'accounts:account_settings' %}">
      {% csrf_token %}
      <div class="form-title-row">
        <h1>User Information</h1>
      </div>
      <div class="form-row {% if form.email.errors %}email-field{% endif %}">
        <label>
          <span>Email</span>
          <input type="email" name="email" value="{{ form.email.value }}" required />
        </label>
        <span class="form-valid-data-sign"><i class="fa fa-check"></i></span>
        <span class="form-invalid-data-sign"><i class="fa fa-close"></i></span>
        <span class="form-invalid-data-info"></span>
      </div>
      <div class="form-row {% if form.first_name.errors %}first-name-field{% endif %}">
        <label>
          <span>First name</span>
          <input type="text" name="first_name" value="{{ form.first_name.value }}" required />
        </label>
        <span class="form-valid-data-sign"><i class="fa fa-check"></i></span>
        <span class="form-invalid-data-sign"><i class="fa fa-close"></i></span>
        <span class="form-invalid-data-info"></span>
      </div>
      <div class="form-row {% if form.last_name.errors %}last-name-field{% endif %}">
        <label>
          <span>Last name</span>
          <input type="text" name="last_name" value="{{ form.last_name.value }}" required />
        </label>
        <span class="form-valid-data-sign"><i class="fa fa-check"></i></span>
        <span class="form-invalid-data-sign"><i class="fa fa-close"></i></span>
        <span class="form-invalid-data-info"></span>
      </div>
      <div class="form-row {% if form.password_new_confirm.errors %}password-field{% endif %}">
        <label>
          <span>New password</span>
          <input type="password" name="password_new" placeholder="New password" />
        </label>
        <span class="form-valid-data-sign"><i class="fa fa-check"></i></span>
        <span class="form-invalid-data-sign"><i class="fa fa-close"></i></span>
        <span class="form-invalid-data-info"></span>
      </div>
      <div class="form-row {% if form.password_new_confirm.errors %}password-field{% endif %}">
        <label>
          <span>Confirm password</span>
          <input type="password" name="password_new_confirm" placeholder="Confirm new password">
        </label>
        <span class="form-valid-data-sign"><i class="fa fa-check"></i></span>
        <span class="form-invalid-data-sign"><i class="fa fa-close"></i></span>
        <span class="form-invalid-data-info"></span>
      </div>
      <div class="form-row">
        <button type="submit">Update</button>
      </div>
    </form>
  </div>

  <div class="col-md-4 col-lg-4 sidebar-gutter">
    <br><br>
    <div class="sidebar-widget">
      <h3 class="sidebar-title">Membership Information</h3>
      <div class="widget-container">
        <p>
          <strong>Plan</strong>: {{ subscription.plan.name }}
        </p>
        <p>
          <strong>Start Date</strong>: {{ subscription.current_period_start }}
        </p>
        <p>
          <strong>End Date</strong>: {{ subscription.current_period_end }}
        </p>
        <p>
          <strong>Auto-Renew</strong>: <span style="margin-left:7px;"><input type="checkbox" id="auto-renew" {% if customer.auto_renew %}checked{% endif %}></span>
        </p>
        {% if not customer.auto_renew %}
          <small>
            <em>
              * Your membership will be deactivated on the end date above, and you will no longer be charged.
            </em>
          </small>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock content %}

{% block scripts %}
  <script>
      $(document).ready(function() {
          var errorField = $('.first-name-field');
          errorField.addClass('form-invalid-data');
          errorField.find('.form-invalid-data-info').text('{% for error in form.first_name.errors %}{{ error }}{% endfor %}');

          var errorField = $('.last-name-field');
          errorField.addClass('form-invalid-data');
          errorField.find('.form-invalid-data-info').text('{% for error in form.last_name.errors %}{{ error }}{% endfor %}');

          var errorField = $('.email-field');
          errorField.addClass('form-invalid-data');
          errorField.find('.form-invalid-data-info').text('{% for error in form.email.errors %}{{ error }}{% endfor %}');

          var errorField = $('.password-field');
          errorField.addClass('form-invalid-data');
          errorField.find('.form-invalid-data-info').text('{% for error in form.password_new_confirm.errors %}{{ error }}{% endfor %}');

          // var successField = $('.form-input-email-row');
          // successField.addClass('form-valid-data');
      });
      $("#auto-renew").click(function(e) {
          e.preventDefault();
          var t = $(this),
              a = $(e.target);
          $.ajax({
              type: "POST",
              url: "{% url 'billing:update_auto_renew' %}",
              data: {
                  csrfmiddlewaretoken: "{{ csrf_token }}"
              },
              dataType: "json",
              beforeSend: function() {
                  $("body").css({"opacity":"0.3", "background-color":"rgb(0, 0, 0)"});
                  $("page-loader").css({"opacity":"1.0"});
                  $('#page-loader').show();
              },
              complete: function(){
                  $('#page-loader').hide();
                  location.reload();
              },
              success: function(e) {

              },
              error: function() {
                  alert("Sorry, there was an error with your request. Please try again later.");
              },
          })
      });
  </script>
{% endblock scripts %}