accounts/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from . import views


app_name = 'accounts'


urlpatterns = [
    url(
        regex=r"^memberships/$",
        view=views.memberships,
        name="memberships"
    ),
    url(
        regex=r"^settings/$",
        view=views.account_settings,
        name="account_settings"
    ),
    url(
        regex=r'^(?P<sponsor_pk>\d+)/$',
        view=views.detail,
        name='detail'
    ),
]

authentication/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from . import views


app_name = 'authentication'


urlpatterns = [
    url(
        regex=r"^login/$",
        view=views.auth_base_view,
        name="auth_base_view"
    ),
    url(
        regex=r"^login/complete/$",
        view=views.auth_login,
        name="auth_login"
    ),
    url(
        regex=r"^memberships/register/$",
        view=views.auth_register,
        name="auth_register"
    ),
    url(
        regex=r"^logout/$",
        view=views.auth_logout,
        name="auth_logout"
    ),
    url(
        regex=r"^password/forgot/$",
        view=views.password_reset,
        name="password_reset"
    ),
    url(
        regex=r"^password/reset/confirm/"
              r"(?P<uidb64>[0-9A-Za-z_\-]+)/"
              r"(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
        view=views.password_reset_confirm,
        name="password_reset_confirm"
    ),
]

trip/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from . import views


admin.site.site_header = "TRIP Administration"
admin.site.site_title = "TRIP Administration"
admin.site.index_title = "TRIP"


urlpatterns = [
    # ADMIN
    url(
        r'^hidden/secure/trip/admin/',
        include(admin.site.urls)
    ),

    # GENERAL
    url(
        regex=r'^$',
        view=views.home,
        name='home'
    ),

    # ACCOUNTS
    url(
        r'^accounts/',
        include('accounts.urls', namespace='accounts')
    ),

    # AUTHENTICATION
    url(
        r'^auth/',
        include('authentication.urls', namespace='authentication')
    ),

    # BILLING
    url(
        r'^billing/',
        include('billing.urls', namespace='billing')
    ),

    # CONTACT
    url(
        r'^contact/',
        include('contact.urls', namespace='contact')
    ),

    # EVENTS
    url(
        r'^events/',
        include('events.urls', namespace='events')
    ),

    # SPONSORS
    url(
        regex=r'^sponsors/$',
        view=views.sponsors,
        name='sponsors'
    ),
]


if settings.DEBUG:
    urlpatterns += [] + static(settings.STATIC_URL,
                               document_root=settings.STATIC_ROOT)
    urlpatterns += [] + static(settings.MEDIA_URL,
                               document_root=settings.MEDIA_ROOT)
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

templates/general/_sidebar.html
{% load staticfiles %}

<div class="col-md-4 sidebar-gutter">
  <aside>
    <!-- account -->
    <div class="sidebar-widget">
      <h3 class="sidebar-title">Account</h3>
      {% if user.is_anonymous %}
        <div class="widget-container">
          {% include 'auth/_login_form.html' %}
        </div>
      {% else %}
        <div class="widget-container widget-about">
          <h4>{{ user.get_full_name }}</h4>
          <div class="author-title">
            <a href="{% url 'accounts:account_settings' %}">edit profile</a>
            <span style="margin: auto 7px;">|</span>
            <a href="{% url 'authentication:auth_logout' %}">sign out</a>
          </div>
          <!-- show profile information -->
        </div>
      {% endif %}
    </div>
    <!-- /account -->

    <!-- featured events -->
    {% if featured_events %}
      <div class="sidebar-widget">
        <h3 class="sidebar-title">Featured Events</h3>
        <div class="widget-container">
          {% for event in featured_events %}
            <article class="widget-post">
              <div class="post-image" style="background:#ccc; width:52px; margin-right:10px; border-radius:10px; padding:5px;">
                <a href="{{ event.get_absolute_url }}">
                  <p class="month" style="margin:0; text-align:center; color:#fff;">
                    {{ event.start_date|date:"N" }}
                  </p>
                  <p class="day" style="font-family:'Helvetica Neue'; text-align:center; color:#fff; font-size:27px; margin:0; line-height:27px; font-weight:bold;">
                    {{ event.start_date.day }}
                  </p>
                </a>
              </div>
              <div class="post-body">
                <h2>
                  <a href="{{ event.get_absolute_url }}">{{ event.name }}</a>
                </h2>
                <div class="post-meta">
                  <span>
                    <i class="fa fa-clock-o"></i> {{ event.event_date }}
                  </span>
                </div>
              </div>
            </article>
          {% endfor %}
        </div>
      </div>
    {% endif %}
    <!-- /featured events -->

    <!-- social links -->
    {% if socials_exist %}
      <div class="sidebar-widget">
        <h3 class="sidebar-title">Follow us!</h3>
        <div class="widget-container">
          <div class="widget-socials">
            {% if facebook_username %}
              <a href="https://www.facebook.com/{{ facebook_username }}">
                <i class="fa fa-facebook"></i>
              </a>
            {% endif %}
            {% if twitter_username %}
              <a href="https://twitter.com/{{ twitter_username }}">
                <i class="fa fa-twitter"></i>
              </a>
            {% endif %}
            {% if instagram_username %}
              <a href="https://www.instagram.com/{{ instagram_username }}">
                <i class="fa fa-instagram"></i>
              </a>
            {% endif %}
            {% if google_plus_username %}
              <a href="https://plus.google.com/+{{ google_plus_username }}">
                <i class="fa fa-google-plus"></i>
              </a>
            {% endif %}
          </div>
        </div>
      </div>
    {% endif %}
    <!-- /social links -->
  </aside>
</div>

templates/general/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block header_content %}
  <header>
    <img src="{% static 'img/default-company-logo.jpg' %}">
  </header>
{% endblock header_content %}

{% block content %}
  <section>
    <div class="row">
      <div class="col-md-8">
        {% if featured_events %}
          <h4 class="text-center" style="font-weight:300; letter-spacing:7px;">
            FEATURED EVENTS
          </h4>
          {% for event in featured_events %}
            <article class="blog-post">
              <div class="blog-post-body">
                <h2>
                  <a href="{{ event.get_absolute_url }}">{{ event.name }}</a>
                </h2>
                <div class="post-meta">
                  <span>
                    <i class="fa fa-clock-o"></i>{{ event.event_date }}
                  </span>
                </div>
                <div class="blog-post-text">
                  {{ event.description|safe|truncatewords_html:75 }}
                </div>
              </div>
            </article>
          {% endfor %}
        {% else %}
          <h2>There are currently no upcoming events at this time.</h2><br>
        {% endif %}
      </div>

      <!-- sidebar -->
      {% include 'general/_sidebar.html' %}
      <!-- /sidebar -->

    </div>
  </section>
{% endblock content %}