contact/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from . import views


app_name = 'contact'


urlpatterns = [
    url(
        regex=r'^$',
        view=views.inquiry,
        name='inquiry'
    ),
    url(
        regex=r"^unsubscribe/"
              r"(?P<email>\w+|[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$",
        view=views.unsubscribe,
        name='unsubscribe'
    )
]

events/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from . import views


app_name = 'events'


urlpatterns = [
    url(
        regex=r'^(?P<event_pk>\d+)/$',
        view=views.detail,
        name='detail'
    ),
    url(
        regex=r'^(?P<event_pk>\d+)/success/$',
        view=views.reg_success,
        name='reg_success'
    ),
    url(
        regex=r'^$',
        view=views.list,
        name='list'
    ),
]

trip/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from . import views


admin.site.site_header = "TRIP Administration"
admin.site.site_title = "TRIP Administration"
admin.site.index_title = "TRIP"


urlpatterns = [
    # ADMIN
    url(
        r'^hidden/secure/trip/admin/',
        include(admin.site.urls)
    ),

    # GENERAL
    url(
        regex=r'^$',
        view=views.home,
        name='home'
    ),

    # ACCOUNTS
    url(
        r'^accounts/',
        include('accounts.urls', namespace='accounts')
    ),

    # AUTHENTICATION
    url(
        r'^auth/',
        include('authentication.urls', namespace='authentication')
    ),

    # BILLING
    url(
        r'^billing/',
        include('billing.urls', namespace='billing')
    ),

    # CONTACT
    url(
        r'^contact/',
        include('contact.urls', namespace='contact')
    ),

    # EVENTS
    url(
        r'^events/',
        include('events.urls', namespace='events')
    ),

    # SPONSORS
    url(
        regex=r'^sponsors/$',
        view=views.sponsors,
        name='sponsors'
    ),
]


if settings.DEBUG:
    urlpatterns += [] + static(settings.STATIC_URL,
                               document_root=settings.STATIC_ROOT)
    urlpatterns += [] + static(settings.MEDIA_URL,
                               document_root=settings.MEDIA_ROOT)
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

events/models.py
from __future__ import unicode_literals

from datetime import datetime

from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible
from django.utils.functional import cached_property
from django.utils.translation import ugettext_lazy as _

from accounts.models import Sponsor
from core.models import TimeStampedModel

# Create your models here.


class Attendee(TimeStampedModel):
    email = models.EmailField(max_length=120)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    class Meta:
        app_label = 'events'
        verbose_name = _('attendee')
        verbose_name_plural = _('attendees')

    def __str__(self):
        return str(self.email)

    @cached_property
    def full_name(self):
        """Returns the first_name plus the last_name, with a space in
        between."""
        return "{0} {1}".format(self.first_name, self.last_name)

    @cached_property
    def event_name(self):
        event = Event.objects.get(attendees__pk=self.pk)
        return str(event.name)


class EventManager(models.Manager):
    def create(self, name, start_date, end_date, member_fee, non_member_fee,
               email_description, **extra_fields):
        """Creates an event."""
        if not name:
            raise ValueError(_('The event must have a name.'))
        elif not start_date:
            raise ValueError(_('The event must have a start date.'))
        elif not end_date:
            raise ValueError(_('The event must have a end date.'))
        elif not int(member_fee) >= 0:
            raise ValueError(_('The event must have a member fee.'))
        elif not int(non_member_fee) >= 0:
            raise ValueError(_('The event must have a non-member fee.'))
        elif not email_description:
            raise ValueError(_('The event must have an email description.'))

        event = self.model(
            name=name, start_date=start_date, end_date=end_date,
            member_fee=member_fee, non_member_fee=non_member_fee,
            email_description=email_description, **extra_fields
        )
        event.save(using=self._db)
        return event

    def active(self):
        """Returns all active events."""
        return super(EventManager, self).get_queryset() \
            .filter(is_active=True) \
            .prefetch_related('sponsors')

    def featured(self, num_returned=None):
        """Returns all featured events.
        Featured events are ordered by closest to their date."""
        return super(EventManager, self).get_queryset() \
            .filter(is_active=True, end_date__gte=timezone.now()) \
            .prefetch_related('sponsors') \
            .order_by('start_date', 'end_date')[:num_returned]

    def own(self, user):
        """Returns all events the user is sponsoring."""
        return super(EventManager, self).get_queryset() \
            .filter(sponsors=user) \
            .prefetch_related('sponsors') \
            .order_by('start_date')


@python_2_unicode_compatible
class Event(TimeStampedModel):
    name = models.CharField(max_length=120)
    description = models.TextField(blank=True,
                                   help_text='You may use HTML tags')
    email_description = models.TextField(help_text='You may use HTML tags')
    member_fee = models.PositiveIntegerField(_('member fee'),
                                             help_text='Enter amount in cents.')
    non_member_fee = models.PositiveIntegerField(_('non-member fee'),
                                                 help_text='Enter amount in cents.')
    sponsors = models.ManyToManyField(Sponsor, related_name='event_sponsors',
                                      blank=True)
    attendees = models.ManyToManyField(Attendee, related_name='event_attendees',
                                       blank=True)

    start_date = models.DateTimeField(_('start date of event'))
    end_date = models.DateTimeField(_('end date of event'))

    is_active = models.BooleanField(default=True)

    objects = EventManager()

    class Meta:
        app_label = 'events'
        verbose_name = _('event')
        verbose_name_plural = _('events')

    def __str__(self):
        return u'{0}'.format(self.name)

    def get_absolute_url(self):
        """Returns the url for the event."""
        return reverse('events:detail', kwargs={'event_pk': self.pk})

    def get_reg_success_url(self):
        """Returns the url for an event after being successfully registered."""
        return reverse('events:reg_success', kwargs={'event_pk': self.pk})

    def get_checkout_url(self):
        """Returns the checkout url for an event."""
        return reverse('billing:checkout', kwargs={'event_pk': self.pk})

    @property
    def event_status(self):
        now = datetime.now()
        start = self.start_date
        if start <= now and self.end_date >= now:
            return _("Happening now")
        elif start >= now:
            return _("Upcoming")
        return _("Completed")

    @cached_property
    def event_date(self):
        start = self.start_date
        end = self.end_date
        if start.date() == end.date():
            return "{0} | {1}-{2}".format(
                start.strftime("%B %d, %Y"),
                start.strftime("%I:%M %p").lstrip('0'),
                end.strftime("%I:%M %p").lstrip('0'))
        return "{0} - {1}".format(
            start.strftime("%B %d, %Y"), end.strftime("%B %d, %Y"))

    @cached_property
    def event_start_date(self):
        d = self.start_date
        # d.strftime("%A | %B %d, %Y | ") + d.strftime("%I:%M %p").lstrip('0')
        return d.strftime("%B %d, %Y | ") + d.strftime("%I:%M %p").lstrip('0')

    @cached_property
    def event_end_date(self):
        d = self.end_date
        # d.strftime("%A | %B %d, %Y | ") + d.strftime("%I:%M %p").lstrip('0')
        return d.strftime("%B %d, %Y | ") + d.strftime("%I:%M %p").lstrip('0')

    @cached_property
    def get_sponsors_info(self):
        """Returns the information for each sponsor of the event."""
        return self.sponsors.values('id', 'name', 'logo', 'website')

    @cached_property
    def get_attendees_info(self):
        """Returns the information for each user registered for the event."""
        return self.attendees.values('id', 'first_name', 'last_name')

    @property
    def sponsor_count(self):
        """Returns the number of sponsors for the event.."""
        return self.get_sponsors_info.count()

    @property
    def attendee_count(self):
        """Returns the number of attendees of the event."""
        return self.get_attendees_info.count()

events/views.py
from django.shortcuts import get_object_or_404, render

from .models import Event

# Create your views here.


def list(request):
    ctx = {
        'events': Event.objects.active(),
        'featured_events': Event.objects.featured(num_returned=5),
    }
    return render(request, 'events/list.html', ctx)


def detail(request, event_pk):
    event = get_object_or_404(Event, pk=event_pk)
    attending = event.attendees.filter(
        email__iexact=request.user.email).exists()
    ctx = {
        'event': event,
        'member_attending': attending
    }
    return render(request, 'events/detail.html', ctx)


def reg_success(request, event_pk):
    event = get_object_or_404(Event, pk=event_pk)
    return render(request, 'events/success.html', {'event': event})

templates/events/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load billing_extras %}

{% block title %} / {{ event.name }}{% endblock title %}

{% block content %}
  <section>
    <div class="row">
      <div class="col-md-8">
        <article class="blog-post">
          <div class="blog-post-body">
            <h2>{{ event.name }}</h2>
            <div class="post-meta">
              <span><i class="fa fa-clock-o"></i>{{ event.event_date }}</span>
            </div>
            <div class="blog-post-text">
              {{ event.description|safe|linebreaksbr }}
            </div>
          </div>
        </article>
      </div>

      <div class="col-md-4 sidebar-gutter">
        <div class="sidebar-widget">
          {% if member_attending %}
            <button class="attend-button attend-disabled" type="button">
              Registered
            </button>
          {% elif event.event_status == 'Completed' %}
            <button class="attend-button attend-disabled" type="button">
              Registration Expired
            </button>
          {% else %}
            <a href="{{ event.get_checkout_url }}">
              <button class="attend-button arrow" type="button">
                Register For Event
              </button>
            </a>
          {% endif %}
        </div>

        <div class="sidebar-widget">
          <h3 class="sidebar-title">Registration Fees</h3>
          <div class="widget-container">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th class="text-left">Price Description</th>
                  <th class="text-right">Amount</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Member Registration</td>
                  <td class="text-right">${{ event.member_fee|divide:"100" }}</td>
                </tr>
                <tr>
                  <td>Non-Member Registration</td>
                  <td class="text-right">${{ event.non_member_fee|divide:"100" }}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

templates/events/list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %} / Events{% endblock title %}

{% block content %}
  <section>
    <div class="row">
      <div class="col-md-8">
        {% if events %}
          {% for event in events %}
            <article class="blog-post">
              <div class="blog-post-body">
                <h2>
                  <a href="{{ event.get_absolute_url }}">{{ event.name }}</a>
                </h2>
                <div class="post-meta">
                  <span>
                    <i class="fa fa-clock-o"></i>{{ event.event_date }}
                  </span>
                </div>
                <div class="blog-post-text">
                  {{ event.description|safe|truncatewords_html:75 }}
                </div>
              </div>
            </article>
          {% endfor %}
        {% else %}
          <h2>There are currently no upcoming events at this time.</h2><br>
        {% endif %}
      </div>

      <!-- sidebar -->
      {% include 'general/_sidebar.html' %}

    </div>
  </section>
{% endblock content %}

templates/events/new_event_email.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  {% spaceless %}
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>{{ event.name }}</title>
    <style type="text/css">
        body { margin: 0; padding: 0; min-width: 100%!important; }
        img { height: auto; }
        .content { width: 100%; max-width: 600px; }
        .header { padding: 40px 30px 20px 30px; }
        .innerpadding { padding: 30px 30px 30px 30px; }
        .borderbottom { border-bottom: 1px solid #f2eeed; }
        .subhead { font-size: 15px; color: #ffffff; font-family: sans-serif; letter-spacing: 3px; }
        .h1, .h2, .bodycopy { color: #153643; font-family: sans-serif; }
        .h1 { font-size: 33px; line-height: 38px; font-weight: bold; }
        .h2 { padding: 0 0 15px 0; font-size: 24px; line-height: 28px; font-weight: bold; }
        .bodycopy { font-size: 16px; line-height: 22px; }
        .button { text-align: center; font-size: 18px; font-family: sans-serif; font-weight: bold; padding: 0 30px 0 30px; }
        .button a { color: #ffffff; text-decoration: none; }
        .footer { padding: 20px 30px 15px 30px; }
        .footercopy { font-family: sans-serif; font-size: 14px; color: #ffffff; }
        .footercopy a { color: #ffffff; text-decoration: underline; }
        @media only screen and (max-width: 550px), screen and (max-device-width: 550px) {
            body .hide { display: none!important; }
            body .buttonwrapper { background-color: transparent!important; }
            body .button { padding: 0px!important; }
            body .button a { background-color: #e05443; padding: 15px 15px 13px!important; }
            body .unsubscribe { display: block; margin-top: 20px; padding: 10px 50px; background: #2f3942; border-radius: 5px; text-decoration: none!important; font-weight: bold; }
        }
    </style>
  </head>

  <body bgcolor="#f6f8f1">
    <table width="100%" bgcolor="#f6f8f1" border="0" cellpadding="0" cellspacing="0">
      <tr>
        <td>
          <table bgcolor="#ffffff" class="content" align="center" cellpadding="0" cellspacing="0" border="0">
            <tr>
              <td bgcolor="#c7d8a7" class="header">
                <table class="col425" align="left" border="0" cellpadding="0" cellspacing="0" style="width: 100%; max-width: 425px;">
                  <tr>
                    <td height="70">
                      <table width="100%" border="0" cellspacing="0" cellpadding="0">
                        <tr>
                          <td class="subhead" style="padding: 0 0 0 3px;">Transaction Risk Insurance Professionals'</td>
                        </tr>
                        <tr>
                          <td class="h1" style="padding: 5px 0 0 0;">{{ event_name }}</td>
                        </tr>
                      </table>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
            <tr>
              <td class="innerpadding borderbottom">
                <table width="100%" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td class="bodycopy">
                      {{ recipient_first_name }},<br><br>
                    </td>
                  </tr>
                  <tr>
                    <td class="bodycopy">
                      {{ event_email_description|safe|linebreaksbr }}
                    </td>
                  </tr>
                </table>
                <br><br>
                <table class="buttonwrapper" bgcolor="#e05443" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td class="button" height="45">
                      <a href="{{ protocol }}://{{ domain }}{{ event_url }}">Register now!</a>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
            {% if event_sponsors %}
              <tr>
                <td class="innerpadding bodycopy borderbottom">
                  <b>Sponsors:</b> {% for obj in event_sponsors %}{% if forloop.last %}{{ obj.name }}{% else %}{{ obj.name }}, {% endif %}{% endfor %}
                </td>
              </tr>
            {% endif %}
            <tr>
              <td class="innerpadding bodycopy">
                Contact <a href="mailto:{{ contact_email }}">{{ contact_email }}</a> for sponsorship or speaking inquiries.
                <br><br>
                Regards!
                <br><br>
                Transaction Risk Insurance Professionals
              </td>
            </tr>
            <tr>
              <td class="footer" bgcolor="#44525f">
                <table width="100%" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td align="center" class="footercopy">
                      &reg; Transaction Risk Insurance Professionals {% now "Y" %}<br/>
                      <a href="{{ protocol }}://{{ domain }}{% url 'contact:unsubscribe' email=recipient_email %}" class="unsubscribe">
                        <font color="#ffffff">Unsubscribe</font>
                      </a>
                      <span class="hide"> from this newsletter</span>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
  {% endspaceless %}
</html>

templates/events/success.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Trip / Registration Success</title>

    <!-- Fonts -->
    <link href="//fonts.googleapis.com/css?family=Montserrat" rel="stylesheet prefetch">
    <link href="//fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet prefetch">
    <!-- Bootstrap -->
    <link href="{% static 'vendors/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <style>
        body {
            background-color: #fff;
            color: #5c5c5c; }
        h5 {
            font-size: 25px; }
        .logo {
            margin-top: 3em; }
        .headline {
            font-size: 55px;
            font-family: 'Montserrat', Arial, sans-serif;
            font-weight: 800;
            line-height: 1.5; }
        .headline-support {
            font-family: 'Open Sans', Arial, sans-serif;
            font-weight: 600;
            line-height: 1.5; }
        .home-btn {
            font-size: 14px;
            font-weight: 400;
            color: #337ab7; }
    </style>
  </head>

  <body>
    <div class="col-md-12">
      <div class="text-center">
        <img class="logo" src="{% static 'img/check.png' %}" alt="Checkmark" />
        <h1 class="headline">Thank you!</h1>
        <h5 class="headline-support">
          You have successfully registered for <em>{{ event.name }}</em>.
          <br>
          We look forward to seeing you there!
        </h5>
        <p style="margin: 6em;">
          <a href="{% url 'home' %}" class="home-btn">&#8592; BACK TO HOME</a>
        </p>
        <p>&#169; Trip. All rights reserved.</p>
      </div>
    </div>
  </body>

</html>